name: 477-env
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py314h2b7f5b3_1
  - brotlicffi=1.2.0.0=py314h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=py314haa95532_0
  - cffi=2.0.0=py314h02ab6af_1
  - charset-normalizer=3.4.4=py314haa95532_0
  - click=8.2.1=py314haa95532_1
  - colorama=0.4.6=py314haa95532_0
  - expat=2.7.3=h885b0b7_3
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.11=py314haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - joblib=1.5.2=py314haa95532_0
  - libexpat=2.7.3=h885b0b7_3
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libmpdec=4.0.0=h827c3e9_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py314h0b37514_0
  - mkl_fft=2.1.1=py314h281c9fe_0
  - mkl_random=1.3.0=py314hdbada53_0
  - narwhals=2.7.0=py314haa95532_0
  - numexpr=2.14.1=py314h2592778_0
  - numpy=2.3.5=py314h0be4137_0
  - numpy-base=2.3.5=py314h96ad93d_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py314haa95532_1
  - pandas=2.3.3=py314hdbada53_1
  - pip=25.3=pyh0d26453_0
  - plotly=6.3.0=py314h56ec5ee_0
  - pycparser=2.23=py314haa95532_0
  - pysocks=1.7.1=py314haa95532_1
  - python=3.14.1=h3bc0a5a_100_cp314
  - python-dateutil=2.9.0post0=py314haa95532_2
  - python-dotenv=1.1.0=py314haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314haa95532_0
  - requests=2.32.5=py314haa95532_1
  - scikit-learn=1.7.2=py314h7b8e219_1
  - scipy=1.16.3=py314h702286f_0
  - six=1.17.0=py314haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - threadpoolctl=3.5.0=py314h56ec5ee_1
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.0=py314haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - win_inet_pton=1.1.0=py314haa95532_1
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\Ben\anaconda3\envs\477-env
